version: '2'
services:
  nginx:
    container_name: nginx
    image: "${DOCKER_IMAGE}:${DOCKER_TAG}"
    volumes:
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/ssl_conf:/etc/nginx/ssl_conf
      - "./data/ssl/sites/${DOMAIN}:/etc/nginx/ssl_certs/${DOMAIN}"
      - "./data/www/${DOMAIN}:/var/www/${DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
